/**
 * Error Code Constants
 * 
 * Auto-generated from backend API
 * DO NOT EDIT MANUALLY
 * 
 * Generated at: 2025-12-17T14:07:27.573Z
 * 
 * Usage:
 *   if (errorCode === ERROR_CODES.AUTH_ACCOUNT_LOCKED) { ... }
 *   
 * Benefits:
 *   - Type-safe error code references
 *   - IDE autocomplete support
 *   - Prevents typos in error code strings
 */

import type { ErrorCode } from "@/lib/types/error-codes";

/**
 * Type-safe constant references for all error codes
 * Organized by category for easier navigation
 */
export const ERROR_CODES: Record<ErrorCode, ErrorCode> = {
    // ASSET
    ASSET_ALREADY_ASSIGNED: "ASSET_ALREADY_ASSIGNED",
    ASSET_CANNOT_DELETE: "ASSET_CANNOT_DELETE",
    ASSET_CODE_EXISTS: "ASSET_CODE_EXISTS",
    ASSET_INVALID_STATUS: "ASSET_INVALID_STATUS",
    ASSET_NOT_AVAILABLE: "ASSET_NOT_AVAILABLE",
    ASSET_NOT_FOUND: "ASSET_NOT_FOUND",

    // AUTH
    AUTH_2FA_REQUIRED: "AUTH_2FA_REQUIRED",
    AUTH_ACCOUNT_INACTIVE: "AUTH_ACCOUNT_INACTIVE",
    AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
    AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
    AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
    AUTH_INVALID_2FA_CODE: "AUTH_INVALID_2FA_CODE",
    AUTH_INVALID_BACKUP_CODE: "AUTH_INVALID_BACKUP_CODE",
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_INVALID_OLD_PASSWORD: "AUTH_INVALID_OLD_PASSWORD",
    AUTH_INVALID_PASSWORD: "AUTH_INVALID_PASSWORD",
    AUTH_INVALID_REFRESH_TOKEN: "AUTH_INVALID_REFRESH_TOKEN",
    AUTH_INVALID_RESET_TOKEN: "AUTH_INVALID_RESET_TOKEN",
    AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
    AUTH_PASSWORD_RESET_SUCCESS: "AUTH_PASSWORD_RESET_SUCCESS",
    AUTH_RESET_EMAIL_SENT: "AUTH_RESET_EMAIL_SENT",
    AUTH_RESET_TOKEN_EXPIRED: "AUTH_RESET_TOKEN_EXPIRED",
    AUTH_RESET_TOKEN_VALID: "AUTH_RESET_TOKEN_VALID",
    AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
    AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    AUTH_WEAK_PASSWORD: "AUTH_WEAK_PASSWORD",

    // DEVICE
    DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
    DEVICE_NOT_TRUSTED_FOR_OPERATION: "DEVICE_NOT_TRUSTED_FOR_OPERATION",

    // EMAIL
    EMAIL_TEMPLATE_BODY_REQUIRED: "EMAIL_TEMPLATE_BODY_REQUIRED",
    EMAIL_TEMPLATE_CODE_EXISTS: "EMAIL_TEMPLATE_CODE_EXISTS",
    EMAIL_TEMPLATE_CODE_REQUIRED: "EMAIL_TEMPLATE_CODE_REQUIRED",
    EMAIL_TEMPLATE_NAME_REQUIRED: "EMAIL_TEMPLATE_NAME_REQUIRED",
    EMAIL_TEMPLATE_NOT_FOUND: "EMAIL_TEMPLATE_NOT_FOUND",
    EMAIL_TEMPLATE_SUBJECT_REQUIRED: "EMAIL_TEMPLATE_SUBJECT_REQUIRED",
    EMAIL_TEMPLATE_SYSTEM_CANNOT_DELETE: "EMAIL_TEMPLATE_SYSTEM_CANNOT_DELETE",
    EMAIL_TEMPLATE_SYSTEM_CANNOT_UPDATE: "EMAIL_TEMPLATE_SYSTEM_CANNOT_UPDATE",

    // GEN
    GEN_CONFLICT: "GEN_CONFLICT",
    GEN_INTERNAL_ERROR: "GEN_INTERNAL_ERROR",
    GEN_INVALID_OPERATION: "GEN_INVALID_OPERATION",
    GEN_NOT_FOUND: "GEN_NOT_FOUND",
    GEN_RATE_LIMITED: "GEN_RATE_LIMITED",
    GEN_SERVICE_UNAVAILABLE: "GEN_SERVICE_UNAVAILABLE",
    GEN_TIMEOUT: "GEN_TIMEOUT",

    // KEY
    KEY_ALREADY_ACTIVE: "KEY_ALREADY_ACTIVE",
    KEY_ALREADY_INACTIVE: "KEY_ALREADY_INACTIVE",
    KEY_ALREADY_REVOKED: "KEY_ALREADY_REVOKED",
    KEY_CANNOT_DELETE_ACTIVE: "KEY_CANNOT_DELETE_ACTIVE",
    KEY_EXPIRED: "KEY_EXPIRED",
    KEY_INVALID_ALGORITHM: "KEY_INVALID_ALGORITHM",
    KEY_INVALID_SIZE: "KEY_INVALID_SIZE",
    KEY_MUST_REVOKE_FIRST: "KEY_MUST_REVOKE_FIRST",
    KEY_NO_ACTIVE_KEY: "KEY_NO_ACTIVE_KEY",
    KEY_NOT_FOUND: "KEY_NOT_FOUND",

    // MENU
    MENU_CIRCULAR_REFERENCE: "MENU_CIRCULAR_REFERENCE",
    MENU_CODE_EXISTS: "MENU_CODE_EXISTS",
    MENU_HAS_CHILDREN: "MENU_HAS_CHILDREN",
    MENU_INVALID_PARENT: "MENU_INVALID_PARENT",
    MENU_MAX_DEPTH_EXCEEDED: "MENU_MAX_DEPTH_EXCEEDED",
    MENU_NOT_FOUND: "MENU_NOT_FOUND",

    // NODE
    NODE_NOT_FOUND: "NODE_NOT_FOUND",

    // ORG
    ORG_CIRCULAR_REFERENCE: "ORG_CIRCULAR_REFERENCE",
    ORG_CODE_EXISTS: "ORG_CODE_EXISTS",
    ORG_HAS_CHILDREN: "ORG_HAS_CHILDREN",
    ORG_HAS_MEMBERS: "ORG_HAS_MEMBERS",
    ORG_INVALID_PARENT: "ORG_INVALID_PARENT",
    ORG_NAME_EXISTS: "ORG_NAME_EXISTS",
    ORG_NOT_FOUND: "ORG_NOT_FOUND",

    // PERMISSION
    PERMISSION_ALREADY_ASSIGNED: "PERMISSION_ALREADY_ASSIGNED",
    PERMISSION_EXISTS: "PERMISSION_EXISTS",
    PERMISSION_INVALID: "PERMISSION_INVALID",
    PERMISSION_NOT_ASSIGNED: "PERMISSION_NOT_ASSIGNED",
    PERMISSION_NOT_FOUND: "PERMISSION_NOT_FOUND",

    // ROLE
    ROLE_ALREADY_ASSIGNED_TO_USER: "ROLE_ALREADY_ASSIGNED_TO_USER",
    ROLE_ASSIGNMENT_INVALID_DATE_RANGE: "ROLE_ASSIGNMENT_INVALID_DATE_RANGE",
    ROLE_ASSIGNMENT_NOT_FOUND: "ROLE_ASSIGNMENT_NOT_FOUND",
    ROLE_CODE_EXISTS: "ROLE_CODE_EXISTS",
    ROLE_IN_USE: "ROLE_IN_USE",
    ROLE_INVALID_RANK: "ROLE_INVALID_RANK",
    ROLE_NAME_REQUIRED: "ROLE_NAME_REQUIRED",
    ROLE_NO_PERMISSIONS_PROVIDED: "ROLE_NO_PERMISSIONS_PROVIDED",
    ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
    ROLE_SYSTEM_ROLE_CANNOT_DELETE: "ROLE_SYSTEM_ROLE_CANNOT_DELETE",
    ROLE_SYSTEM_ROLE_CANNOT_UPDATE: "ROLE_SYSTEM_ROLE_CANNOT_UPDATE",

    // SETTING
    SETTING_INVALID_VALUE: "SETTING_INVALID_VALUE",
    SETTING_KEY_EXISTS: "SETTING_KEY_EXISTS",
    SETTING_NOT_EDITABLE: "SETTING_NOT_EDITABLE",
    SETTING_NOT_FOUND: "SETTING_NOT_FOUND",
    SETTING_VALUE_REQUIRED: "SETTING_VALUE_REQUIRED",

    // STOR
    STOR_FILE_NOT_FOUND: "STOR_FILE_NOT_FOUND",
    STOR_FILE_TOO_LARGE: "STOR_FILE_TOO_LARGE",
    STOR_FILE_TYPE_NOT_ALLOWED: "STOR_FILE_TYPE_NOT_ALLOWED",
    STOR_QUOTA_EXCEEDED: "STOR_QUOTA_EXCEEDED",
    STOR_SESSION_EXPIRED: "STOR_SESSION_EXPIRED",
    STOR_SESSION_NOT_FOUND: "STOR_SESSION_NOT_FOUND",

    // USER
    USER_ALREADY_ACTIVE: "USER_ALREADY_ACTIVE",
    USER_ALREADY_INACTIVE: "USER_ALREADY_INACTIVE",
    USER_CANNOT_DELETE_SELF: "USER_CANNOT_DELETE_SELF",
    USER_EMAIL_EXISTS: "USER_EMAIL_EXISTS",
    USER_INVALID_EMAIL: "USER_INVALID_EMAIL",
    USER_INVALID_PHONE: "USER_INVALID_PHONE",
    USER_INVALID_USERNAME: "USER_INVALID_USERNAME",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_PHONE_EXISTS: "USER_PHONE_EXISTS",
    USER_SESSION_NOT_FOUND: "USER_SESSION_NOT_FOUND",
    USER_USERNAME_EXISTS: "USER_USERNAME_EXISTS",

    // VAL
    VAL_2FA_CODE_INVALID_FORMAT: "VAL_2FA_CODE_INVALID_FORMAT",
    VAL_2FA_CODE_INVALID_LENGTH: "VAL_2FA_CODE_INVALID_LENGTH",
    VAL_2FA_CODE_REQUIRED: "VAL_2FA_CODE_REQUIRED",
    VAL_2FA_SESSION_REQUIRED: "VAL_2FA_SESSION_REQUIRED",
    VAL_AUTH_METHOD_INVALID: "VAL_AUTH_METHOD_INVALID",
    VAL_AUTH_METHOD_REQUIRED: "VAL_AUTH_METHOD_REQUIRED",
    VAL_BACKUP_CODE_REQUIRED: "VAL_BACKUP_CODE_REQUIRED",
    VAL_CONFIRM_PASSWORD_REQUIRED: "VAL_CONFIRM_PASSWORD_REQUIRED",
    VAL_CURRENT_PASSWORD_REQUIRED: "VAL_CURRENT_PASSWORD_REQUIRED",
    VAL_DUPLICATE: "VAL_DUPLICATE",
    VAL_EMAIL_INVALID: "VAL_EMAIL_INVALID",
    VAL_EMAIL_OTP_INVALID_FORMAT: "VAL_EMAIL_OTP_INVALID_FORMAT",
    VAL_EMAIL_OTP_INVALID_LENGTH: "VAL_EMAIL_OTP_INVALID_LENGTH",
    VAL_EMAIL_OTP_REQUIRED: "VAL_EMAIL_OTP_REQUIRED",
    VAL_EMAIL_REQUIRED: "VAL_EMAIL_REQUIRED",
    VAL_EMAIL_TOO_LONG: "VAL_EMAIL_TOO_LONG",
    VAL_IDENTITY_REQUIRED: "VAL_IDENTITY_REQUIRED",
    VAL_IDENTITY_TOO_LONG: "VAL_IDENTITY_TOO_LONG",
    VAL_IDENTITY_TOO_SHORT: "VAL_IDENTITY_TOO_SHORT",
    VAL_INVALID_FORMAT: "VAL_INVALID_FORMAT",
    VAL_INVALID_VALUE: "VAL_INVALID_VALUE",
    VAL_NEW_PASSWORD_NO_DIGIT: "VAL_NEW_PASSWORD_NO_DIGIT",
    VAL_NEW_PASSWORD_NO_LOWERCASE: "VAL_NEW_PASSWORD_NO_LOWERCASE",
    VAL_NEW_PASSWORD_NO_SPECIAL: "VAL_NEW_PASSWORD_NO_SPECIAL",
    VAL_NEW_PASSWORD_NO_UPPERCASE: "VAL_NEW_PASSWORD_NO_UPPERCASE",
    VAL_NEW_PASSWORD_REQUIRED: "VAL_NEW_PASSWORD_REQUIRED",
    VAL_NEW_PASSWORD_TOO_LONG: "VAL_NEW_PASSWORD_TOO_LONG",
    VAL_NEW_PASSWORD_TOO_SHORT: "VAL_NEW_PASSWORD_TOO_SHORT",
    VAL_OUT_OF_RANGE: "VAL_OUT_OF_RANGE",
    VAL_PASSWORD_REQUIRED: "VAL_PASSWORD_REQUIRED",
    VAL_PASSWORD_TOO_LONG: "VAL_PASSWORD_TOO_LONG",
    VAL_PASSWORD_TOO_SHORT: "VAL_PASSWORD_TOO_SHORT",
    VAL_PASSWORDS_MISMATCH: "VAL_PASSWORDS_MISMATCH",
    VAL_RECOVERY_CODE_REQUIRED: "VAL_RECOVERY_CODE_REQUIRED",
    VAL_RECOVERY_CODE_TOO_LONG: "VAL_RECOVERY_CODE_TOO_LONG",
    VAL_RECOVERY_CODE_TOO_SHORT: "VAL_RECOVERY_CODE_TOO_SHORT",
    VAL_REFRESH_TOKEN_REQUIRED: "VAL_REFRESH_TOKEN_REQUIRED",
    VAL_REQUIRED: "VAL_REQUIRED",
    VAL_RESET_TOKEN_REQUIRED: "VAL_RESET_TOKEN_REQUIRED",
    VAL_TOO_LONG: "VAL_TOO_LONG",
    VAL_TOO_SHORT: "VAL_TOO_SHORT",
    VAL_USERNAME_REQUIRED: "VAL_USERNAME_REQUIRED",
    VAL_USERNAME_TOO_LONG: "VAL_USERNAME_TOO_LONG",
    VAL_USERNAME_TOO_SHORT: "VAL_USERNAME_TOO_SHORT",

    // VO
    VO_ADDRESS_CITY_EMPTY: "VO_ADDRESS_CITY_EMPTY",
    VO_ADDRESS_COUNTRY_EMPTY: "VO_ADDRESS_COUNTRY_EMPTY",
    VO_ADDRESS_STREET_EMPTY: "VO_ADDRESS_STREET_EMPTY",
    VO_ASSET_TAG_EMPTY: "VO_ASSET_TAG_EMPTY",
    VO_ASSET_TAG_TOO_LONG: "VO_ASSET_TAG_TOO_LONG",
    VO_COST_CENTER_EMPTY: "VO_COST_CENTER_EMPTY",
    VO_COST_CENTER_TOO_LONG: "VO_COST_CENTER_TOO_LONG",
    VO_COUNTRY_CODE_EMPTY: "VO_COUNTRY_CODE_EMPTY",
    VO_COUNTRY_CODE_INVALID: "VO_COUNTRY_CODE_INVALID",
    VO_DATE_INVALID: "VO_DATE_INVALID",
    VO_DATE_RANGE_INVALID: "VO_DATE_RANGE_INVALID",
    VO_DEPRECIATION_LIFE_INVALID: "VO_DEPRECIATION_LIFE_INVALID",
    VO_DEPRECIATION_METHOD_EMPTY: "VO_DEPRECIATION_METHOD_EMPTY",
    VO_DEPRECIATION_RESIDUAL_INVALID: "VO_DEPRECIATION_RESIDUAL_INVALID",
    VO_DIMENSION_INVALID: "VO_DIMENSION_INVALID",
    VO_DIMENSION_UNIT_EMPTY: "VO_DIMENSION_UNIT_EMPTY",
    VO_DOMAIN_EMPTY: "VO_DOMAIN_EMPTY",
    VO_DOMAIN_INVALID: "VO_DOMAIN_INVALID",
    VO_DOMAIN_TOO_LONG: "VO_DOMAIN_TOO_LONG",
    VO_EMAIL_EMPTY: "VO_EMAIL_EMPTY",
    VO_EMAIL_INVALID: "VO_EMAIL_INVALID",
    VO_EMAIL_TOO_LONG: "VO_EMAIL_TOO_LONG",
    VO_INSURANCE_POLICY_EMPTY: "VO_INSURANCE_POLICY_EMPTY",
    VO_INSURANCE_VALUE_INVALID: "VO_INSURANCE_VALUE_INVALID",
    VO_IP_EMPTY: "VO_IP_EMPTY",
    VO_IP_INVALID: "VO_IP_INVALID",
    VO_MAC_EMPTY: "VO_MAC_EMPTY",
    VO_MAC_INVALID: "VO_MAC_INVALID",
    VO_MONEY_CURRENCY_EMPTY: "VO_MONEY_CURRENCY_EMPTY",
    VO_MONEY_CURRENCY_INVALID: "VO_MONEY_CURRENCY_INVALID",
    VO_MONEY_NEGATIVE: "VO_MONEY_NEGATIVE",
    VO_PASSWORD_EMPTY: "VO_PASSWORD_EMPTY",
    VO_PASSWORD_NO_DIGIT: "VO_PASSWORD_NO_DIGIT",
    VO_PASSWORD_NO_LOWERCASE: "VO_PASSWORD_NO_LOWERCASE",
    VO_PASSWORD_NO_NUMBER: "VO_PASSWORD_NO_NUMBER",
    VO_PASSWORD_NO_SPECIAL: "VO_PASSWORD_NO_SPECIAL",
    VO_PASSWORD_NO_UPPERCASE: "VO_PASSWORD_NO_UPPERCASE",
    VO_PASSWORD_TOO_LONG: "VO_PASSWORD_TOO_LONG",
    VO_PASSWORD_TOO_SHORT: "VO_PASSWORD_TOO_SHORT",
    VO_PERCENTAGE_EXCEED: "VO_PERCENTAGE_EXCEED",
    VO_PERCENTAGE_NEGATIVE: "VO_PERCENTAGE_NEGATIVE",
    VO_PERCENTAGE_OUT_OF_RANGE: "VO_PERCENTAGE_OUT_OF_RANGE",
    VO_PHONE_EMPTY: "VO_PHONE_EMPTY",
    VO_PHONE_INVALID: "VO_PHONE_INVALID",
    VO_POSTAL_CODE_EMPTY: "VO_POSTAL_CODE_EMPTY",
    VO_POSTAL_CODE_INVALID: "VO_POSTAL_CODE_INVALID",
    VO_RATING_OUT_OF_RANGE: "VO_RATING_OUT_OF_RANGE",
    VO_RESOURCE_ACTION_EMPTY: "VO_RESOURCE_ACTION_EMPTY",
    VO_RESOURCE_ACTION_TOO_LONG: "VO_RESOURCE_ACTION_TOO_LONG",
    VO_RESOURCE_TYPE_EMPTY: "VO_RESOURCE_TYPE_EMPTY",
    VO_RESOURCE_TYPE_TOO_LONG: "VO_RESOURCE_TYPE_TOO_LONG",
    VO_ROLE_CODE_EMPTY: "VO_ROLE_CODE_EMPTY",
    VO_ROLE_CODE_INVALID: "VO_ROLE_CODE_INVALID",
    VO_ROLE_CODE_TOO_LONG: "VO_ROLE_CODE_TOO_LONG",
    VO_SERIAL_EMPTY: "VO_SERIAL_EMPTY",
    VO_SERIAL_INVALID: "VO_SERIAL_INVALID",
    VO_TAX_CODE_EMPTY: "VO_TAX_CODE_EMPTY",
    VO_TAX_CODE_INVALID: "VO_TAX_CODE_INVALID",
    VO_TAX_CODE_TOO_LONG: "VO_TAX_CODE_TOO_LONG",
    VO_TAX_CODE_TOO_SHORT: "VO_TAX_CODE_TOO_SHORT",
    VO_URL_EMPTY: "VO_URL_EMPTY",
    VO_URL_INVALID: "VO_URL_INVALID",
    VO_USERNAME_EMPTY: "VO_USERNAME_EMPTY",
    VO_USERNAME_INVALID: "VO_USERNAME_INVALID",
    VO_USERNAME_TOO_LONG: "VO_USERNAME_TOO_LONG",
    VO_USERNAME_TOO_SHORT: "VO_USERNAME_TOO_SHORT",
    VO_WARRANTY_DURATION_INVALID: "VO_WARRANTY_DURATION_INVALID",
};

/**
 * Type for getting keys from ERROR_CODES object
 * Useful for autocomplete when referencing error codes
 */
export type ErrorCodeKey = keyof typeof ERROR_CODES;

/**
 * Check if a value is a valid error code key
 */
export function isErrorCodeKey(key: string): key is ErrorCodeKey {
    return key in ERROR_CODES;
}
